apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: trending-aggregator
  namespace: streammind
spec:
  image: streammind-flink:latest
  flinkVersion: v1_18
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/usrlib/flink-jobs.jar
    entryClass: com.streammind.flink.TrendingAggregationJob
    parallelism: 2
    upgradeMode: stateless