apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: streammind-ingress
  namespace: streammind
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - streammind.local
    secretName: self-signed-tls
  rules:
  - host: streammind.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 8000